const GAME_CLICK_ONE_BUTTON = 'CLICK_ONE_BUTTON';

const GAME_LINK_NETWORK = 'LINK_NETWORK';

const GAME_AUTO_CAPTURE_POKEMON = 'AUTO_CAPTURE_POKEMON';

const GAME_ACTION_RESPONSE = 'ACTION_RESPONSE';

const GAME_LOADING = 'LOADING';

const GAME_LOADING_MAP = {
  A: 1,
  B: 2,
  LINK_NETWORK: 3,
  BATTLE: 4
};

export {
  GAME_CLICK_ONE_BUTTON,
  GAME_LINK_NETWORK,
  GAME_AUTO_CAPTURE_POKEMON,
  GAME_ACTION_RESPONSE,
  GAME_LOADING,
  GAME_LOADING_MAP
};