const GAME_CLICK_ONE_BUTTON = 'CLICK_ONE_BUTTON';

const GAME_LINK_NETWORK = 'LINK_NETWORK';

const GAME_AUTO_CAPTURE_POKEMON = 'AUTO_CAPTURE_POKEMON';

const GAME_ACTION_RESPONSE = 'ACTION_RESPONSE';

const GAME_LOADING = 'LOADING';

const GAME_LINK_EXCHANGE = 'LINK_EXCHANGE';

const GAME_STOP_ACTIVE = 'STOP_ACTIVE';

const GAME_START_EXCHANGE = 'START_EXCHANGE';

const GAME_LOADING_MAP = {
  A: 'A',
  B: 'B',
  LINK_NETWORK: 'LINK_NETWORK',
  BATTLE: 'BATTLE',
  LINK_EXCHANGE: 'LINK_EXCHANGE',
  STOP_ACTIVE: 'STOP_ACTIVE',
  START_EXCHANGE: 'START_EXCHANGE',
};

export {
  GAME_CLICK_ONE_BUTTON,
  GAME_LINK_NETWORK,
  GAME_AUTO_CAPTURE_POKEMON,
  GAME_ACTION_RESPONSE,
  GAME_LINK_EXCHANGE,
  GAME_LOADING,
  GAME_START_EXCHANGE,
  GAME_STOP_ACTIVE,
  GAME_LOADING_MAP
};