cors:
  - *
host: 0.0.0.0
port: 8582
authKey: mirai-bot-liujie
cacheSize: 4096
enableWebsocket: true
report: 
  enable: true
  groupMessage: 
    report: true
  friendMessage: 
    report: true
  tempMessage: 
    report: true
  eventMessage: 
    report: true
  destinations: []
  extraHeaders:
{}

heartbeat: 
  enable: true
  delay: 1000
  period: 15000
  destinations: []
  extraBody:
{}

  extraHeaders:
{}
